### ISSUE TITLE
PIP4048 PV Input Power

### ISSUE THREAD

**Issue by relubbe** [opengd/solar-sis#10]
Good day,

The "PV input power" seems to be missing in the Undefinedquery_general_status. It is part of the raw data, but isn't referred to in the calls.json file.

Here is a raw data packet just captured: 241.8 50.1 230.0 50.1 0667 0605 015 455 57.20 003 100 0060 0014 071.5 57.33 00000 00110110 00 00 00831 110�8 Length: 115

The PV input power is 00831 watts.

Here is the object sent to influx: undefinedquery_general_status grid_voltage=241.8,grid_frecuency=50.1,ac_output_voltage=230,ac_output_frecuency=50.1,ac_output_power_va=667,ac_output_active_power=605,output_load_percent=15,bus_voltage=455,battery_voltage=57.2,battery_charging_current=3,battery_capacity=100,inverter_heat_sink_temperature=60,pv_input_current_for_battery=14,pv_input_voltage_1=71.5,battery_voltage_from_scc=57.33,battery_discharge_current=0,device_status=00110110,charging_scc=1,charging_ac=1,charging_scc_acc=0

**Comment by Josuan** [comment]
hi relubbe the way i do it is, field(pv_input_current_for_battery) mean() math (*mean(pv_input_voltage_1))
![Screenshot from 2019-05-27 15-17-15](https://user-images.githubusercontent.com/5648466/58436280-8bc47780-8092-11e9-9f70-0b6b73e69a12.png)
