### ISSUE TITLE
support PCM60x set commands

### ISSUE THREAD

**Issue by frnandu** [opengd/solar-sis#2]
would be nice to be able to programatically set the charger max voltage

here's the spec: https://github.com/tylerjaywilson/Solar-Panel-System/blob/master/Charge-Controller/Solar%20Charge%20Controler%20-%20PCM60X%20-%20RS232%20Protoco.pdf

I'll try to add the commands to the json files and submit another pull request in next few days

**Comment by frnandu** [comment]
Ok, I added:
- QPIRI command for gathering settings.
- a few set commands for bulk/float voltages and max charging current
would be great if you can review the changes and accept them to master.

here's the commit on my fork:
https://github.com/opengd/solar-sis/commit/c3dd5c0d7687097f9f1f81aa2f09becd748f6b16

**Comment by daromer2** [comment]
Thanks
