### ISSUE TITLE
 query daily solar and ac out kwh 

### ISSUE THREAD

**Issue by Josuan** [opengd/solar-sis#21]
can a query of daily solar kwh production and inverter kwh be done in session.json? thanks in advance

**Comment by daromer2** [comment]
Depends on what protocol is used and IF the inverter you have supporta the 
value. IF not use influxdb

Den 24 februari 2020 00:51:39 skrev Josuan <notifications@github.com>:

**Comment by cybertza** [comment]
Do you have the Q for influxdb for that? i was considering rather using emon cms to display.

**Comment by Josuan** [comment]
im using the pip4048 example folder, my inverter is a 5048gk

**Comment by cybertza** [comment]
You can also write the values to EmonCMS and get the values from there, i found it a bit easier when i was using this.

**Comment by daromer2** [comment]
to get a total number of something use integral in influxdb. Ie calculate the area of something. Thats the easiest if the inverter doesnt support it.
