### ISSUE TITLE
How to change measurement

### ISSUE THREAD

**Issue by kasperbirk** [opengd/solar-sis#8]
Hello
When posting data to influx it automatically using the measurement "solar". I want to change that to "inverter-1" but can't figure out where...

Can anyone help?

Thanks in advance

/Kasper

**Comment by daromer2** [comment]
Added influx_pre to the session.json file for easier to handle the solar variable. Feel free to use that version. Note that you need to change the config for the hosts used since i managed to overwrite that.

**Comment by daromer2** [comment]
https://github.com/opengd/solar-sis/commit/7d577f5e74ae6a76b5650dbd0977af27f58f0890
